In [ ]:
**Install NumpyIn [93]:

pip install numpy

#`Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (1.18.5)`
Import NumpyIn [0]:

import numpy as np
'Create single dimensional array with numpy'

single_array = np.array([7,8,9])
print("Single dimensional array using Numpy", single_array)

Single dimensional array using Numpy [7 8 9]
Create Multi dimensional array with numpyIn [96]:

multi_dimensional=np.array([(8,9,10),(11,12,13)])
print("Multi dimensional array using Numpy:")
print(multi_dimensional)`

Multi dimensional array using Numpy:
[[ 8  9 10]
 [11 12 13]]

#Check the dimension of the array with numpy

print('diemnsion of the array:', single_array.ndim)

dimension of the array: 1

print('diemnsion of the array:', multi_dimensional.ndim)

diemnsion of the array: 2

#Check the memory size of the array with numpy

print('Memory size of the array:', single_array.itemsize)

Memory size of the array: 8

print('Memory size of the array:', multi_dimensional.itemsize)

Memory size of the array: 8

#Check the type of the array with numpy

print('Type of the array:', single_array.dtype)

Type of the array: int64

print('Type of the array:', multi_dimensional.dtype)

Type of the array: int64

#Check the size of the array with numpy

print('Total elements present in the array:', single_array.size)`

Total elements present in the array: 3

print('Total elements present in the array:', multi_dimensional.size)

Total elements present in the array: 6

#Check the shape of the array with numpy

print("Shape of the array: ",single_array.shape)
print("It means that the array has 1 dimensions, and each dimension has 3 elements")`

Shape of the array:  (3,)
#It means that the array has 1 dimensions, and each dimension has 3 elements

print("Shape of the array: ",multi_dimensional.shape)
print("It means that the array has 2 dimensions, and each dimension has 3 elements")`

Shape of the array:  (2, 3)
#It means that the array has 2 dimensions, and each dimension has 3 elements`

#Reshape the array with numpy

reshape_array=multi_dimensional.reshape(3,2)
print(reshape_array)
print("It means that the array has 3 dimensions, and each dimension has 2 elements")`

[[ 8  9]
 [10 11]
 [12 13]]
#It means that the array has 3 dimensions, and each dimension has 2 elements`

#Traverse through the array with numpy

for i in single_array:
  print(i)

7
8
9

#Iterating 2D Array

for x in multi_dimensional:
  for y in x:
    print(y)

8
9
10
11
12
13

#Concat two array

first_array = np.array([90, 12, 13])

second_array = np.array([14, 15, 16])

new_array = np.concatenate((first_array,second_array))

print(new_array)

[90 12 13 14 15 16]

#Sort array with Numpy

print('sorted order: ', np.sort(new_array))

sorted order:  [12 13 14 15 16 90]

#Array indexing with Numpy

print('First element start with O in array:', new_array[0])

First element start with O in array: 90

print(multi_dimensional)
print('First element of second dimension:', multi_dimensional[1,0])

[[ 8  9 10]
 [11 12 13]]
First element of second dimension: 11

#Array Slicing with Numpy

print(new_array)
print('Starts from 1 index to go till 4', new_array[1:5])`

[90 12 13 14 15 16]
Starts from 1 index to go till 4 [12 13 14 15]

print(multi_dimensional)
print('second dimension starts from 1 index to go till 2', multi_dimensional[1,1:3])`

[[ 8  9 10]
 [11 12 13]]
second dimension starts from 1 index to go till 2 [12 13]

#Find the max, min value from the array

print('maximum element of the array: ', multi_dimensional.max())
print('minimum element of the array: ', multi_dimensional.min())

maximum element of the array:  13
minimum element of the array:  8

#Linespace with Numpy

array= np.linspace(4,7,5)
print("it will print 5 random value between 4 to 7: ", array)

it will print 5 random value between 4 to 7:  [4.   4.75 5.5  6.25 7.  ]**




# Pandas

**Import PandasIn [0]:

import pandas as pd

#Creating Dataframe using Pandas

df=pd.DataFrame({'Name':['Bob','Sam','Anne','Prit','jyoti','Subhankar'],'Marks':[76,25,94,90,89,67]})
print(df)

        Name  Marks
0        Bob     76
1        Sam     25
2       Anne     94
3       Prit     90
4      jyoti     89
5  Subhankar     67

# Panda's Built in Function to Manipulate Dataframe

print('It will display first 5 records from the data',df.head())

It will display first 5 records from the data     Name  Marks
0    Bob     71    
1    Sam     25
2   Anne     94
3   Prit     90
4  jyoti     89
In [122]

print('It will display last 5 records from the data',df.tail())

It will display last 5 records from the data         Name  Marks
1        Sam     25
2       Anne     94
3       Prit     90
4      jyoti     89
5  Subhankar     67
In [123]:

print('Shape will dispaly the number of total rows and columns',df.shape)

# Shape will dispaly the number of total rows and columns (6, 2)


print('Statistical measurement',df.describe())

Statistical measurement            Marks
count   6.000000
mean   73.500000
std    25.820534
min    25.000000
25%    69.250000
50%    82.500000
75%    89.750000
max    94.000000

# Drop row from the DataframeIn [125]:

new=df
new.drop([0,1,2],axis=0)*

#for rows axis=0*`Out[125]:NameMarks3Prit904jyoti895Subhankar67Drop column from the Dataframe

dnew=df
dnew.drop('Marks',axis=1)
# output
Name0Bob1Sam2Anne3Prit4jyoti5Subhankar**